/* page for adding movies */

import * as React from "react";
import axios from "axios";
import { styled } from "@mui/material/styles";
import Button from "@mui/material/Button";
import CloudUploadIcon from "@mui/icons-material/CloudUpload";
import FormGroup from "@mui/material/FormGroup";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";
import { lightBlue } from "@mui/material/colors";
import { useState } from "react";

export default function AddMovie() {
  const [movie, setMovie] = useState({
    //m_id: 0, // You can leave this blank if it's auto-generated by the backend
    m_isbn: "",
    m_title: "",
    m_director: "",
    m_producer: "",
    m_poster: "",
    m_image1: "",
    m_image2: "",
    mt_id: 0, // Initialize with a default value or leave it blank
    m_reviews: 0,
    m_category: "",
    m_cast: "",
    m_synopsis: "",
    m_showing: 0,
    m_trailer: "",
    m_mark: "",
  });

  async function handleSubmit(e) {
    if (
      movie.m_isbn === "" ||
      movie.m_title === "" ||
      movie.m_director === "" ||
      movie.m_producer === "" ||
      movie.m_poster === "" ||
      movie.m_image1 === "" ||
      movie.m_image2 === "" ||
      movie.m_synopsis === "" ||
      movie.m_trailer === ""
    ) {
      alert("Please Fill out all Fields");
      return;
    }
    e.preventDefault();
    // window.location.assign("http://localhost:3000/manage");
    // alert("Movie Added")
    try {
      const response = await axios.post(
        "http://localhost:8080/api/movie/add",
        movie
      );

      if (response.status === 200) {
        // Movie added successfully
        console.log("Movie added successfully");
        alert("Movie Added");
      } else {
        // Handle errors
        console.error("Failed to add movie");
        alert("Movie Failed to Added");
      }
    } catch (error) {
      console.error("An error occurred:", error);
      alert("ERROR");
    }
    window.location.assign("http://localhost:3000/manage");
  }

  return (
    <body style={{ backgroundColor: "crimson" }}>
      <h1 style={{ fontSize: "30px", color: "black", padding: "20px" }}>
        Add Movie
      </h1>
      <form onSubmit={handleSubmit}>
        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Movie Title :<label htmlFor="movieTitle"></label>
          <input
            type="text"
            name="m_title"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_title: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Movie ISBN :<label htmlFor="movieIsbn"></label>
          <input
            type="text"
            name="m_isbn"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_isbn: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Producer :<label htmlFor="producer"></label>
          <input
            type="text"
            name="m_producer"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_producer: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Director :<label htmlFor="director"></label>
          <input
            type="text"
            name="m_director"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_director: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Cast :<label htmlFor="cast"></label>
          <input
            type="text"
            name="m_cast"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_cast: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Category :<label htmlFor="category"></label>
          <input
            type="text"
            name="m_category"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_category: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Poster URL :<label htmlFor="poster"></label>
          <input
            type="text"
            name="m_poster"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_poster: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Image1 URL :<label htmlFor="image1"></label>
          <input
            type="text"
            name="m_image1"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_image1: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Image2 URL :<label htmlFor="image2"></label>
          <input
            type="text"
            name="m_image2"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_image2: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Trailer URL :<label htmlFor="trailer"></label>
          <input
            type="text"
            name="m_trailer"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_trailer: event.target.value,
              });
            }}
          />
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          MPAA-US film rating code :
          <select
            name="m_mark"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_mark: event.target.value,
              });
            }}
          >
            <option value="G">G</option>
            <option value="PG-13">PG-13</option>
            <option value="R">R</option>
            <option value="Adult">18+</option>
          </select>
        </div>

        <div
          className="registerformat"
          style={{ padding: "20px", color: "black" }}
        >
          Review Ratings :
          <select
            name="m_reviews"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_reviews: event.target.value,
              });
            }}
          >
            <option value={0}>0</option>
            <option value={1}>1</option>
            <option value={2}>2</option>
            <option value={3}>3</option>
            <option value={4}>4</option>
            <option value={5}>5</option>
          </select>
        </div>

        <div style={{ padding: "20px", color: "black" }}>
          <h1>Synopsis :</h1>
          <label htmlFor="description"></label>
          <textarea
            rows={10}
            cols={50}
            name="m_synopsis"
            onChange={(event) => {
              setMovie({
                ...movie,
                m_synopsis: event.target.value,
              });
            }}
          />
        </div>

        <div
          style={{
            display: "flex",
            justifyContent: "center",
            padding: "20px",
            color: "black",
          }}
        >
          <FormGroup>
            <FormControlLabel
              control={
                <Checkbox
                  name="m_showing"
                  checked={movie.m_showing === 1} // Check if movie.m_showing is 1
                  onChange={(event) => {
                    const newValue = event.target.checked ? 1 : 0; // If checked, set to 1; otherwise, set to 0
                    setMovie({
                      ...movie,
                      m_showing: newValue,
                    });
                    console.log("m_showing:", newValue);
                  }}
                  sx={{
                    color: lightBlue[800],
                    "&.Mui-checked": { color: lightBlue[600] },
                  }}
                />
              }
              label="Currenty Showing"
            />
          </FormGroup>
        </div>

        <button type="submit" className="submit-btn" onClick={handleSubmit}>
          Submit
        </button>
      </form>
    </body>
  );
}
